#spring.datasource.url=jdbc:h2:mem:sniperdb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- CONFIGURAÇÃO POSTGRESQL (DOCKER) ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/consigsniper
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURAÇÃO FINAL DOCKER (USER: POSTGRES) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/consigsniper
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração de Upload de Arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
