spring.application.name=consig

# Configuração Exata do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/consigsniper
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Forçando o Dialeto do Hibernate para evitar o erro "JDBC metadata"
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
